- .github/workflows/github-actions-demo.yml
- .github/workflows/lint.yaml
ESLint run repository corrected. 
Addition of github action exmaple to try the process.
> GitHub actions add and modifications.

- .github/workflows/eslint.yml
- web_app_frontend/eslint.config.js
- web_app_frontend/package-lock.json
- web_app_frontend/package.json
Adding ESLint and creating github actions.
> Feature project setup

- web_app_backend/go.mod
/backend
├── /api
│    ├── api.go
│    ├── routes.go
│    └── handlers.go
├── /config
│    └── config.go
├── /controllers
│    ├── userController.go
│    ├── gameController.go
│    └── authController.go
├── /models
│    ├── user.go
│    ├── game.go
│    └── score.go
├── /database
│    └── database.go
├── /middleware
│    └── authMiddleware.go
├── /services
│    ├── authService.go
│    ├── gameService.go
│    └── scoreService.go
├── main.go
>  organisation du backend

- web_app_frontend/src/components/ConnectionPage.vue
- web_app_frontend/src/components/HomePage.vue
- web_app_frontend/src/components/PlayPage.vue
- web_app_frontend/src/components/ScoresPage.vue
- web_app_frontend/src/main.js
- web_app_frontend/src/router/index.js
Added home, scores and play page and link between this pages. Still need to link connection and home page properly.
> Added home, scores and play page

- .github/workflows/project_pipeline.yml
from run dev to run build. This avoid runing idefinitly.
> Updated project pipeline, modified the way to test the frontend

- README.md
- web_app_frontend/src/components/ConnectionPage.vue
- web_app_frontend/src/components/SignUpPage.vue
- web_app_frontend/src/router/index.js
connection page. Implemented the logic to
communicate with backend. Backend not ready, thus
the api calls still needs to be checked.
> Create a sign up page and linked it with

- README.md
- web_app_frontend/.eslintignore
- web_app_frontend/.eslintrc
- web_app_frontend/README.md
- web_app_frontend/eslint.config.mjs
- web_app_frontend/package.json
- web_app_frontend/src/components/GameScores.vue
- web_app_frontend/src/components/LogIn.vue
- web_app_frontend/src/components/PlayGame.vue
- web_app_frontend/src/router/index.js
Added new linter settings and configuration for frontend.
> Feature connection page

- web_app_backend/api/api.go
- web_app_backend/controllers/gameController.go
- web_app_backend/controllers/scoreController.go
- web_app_backend/controllers/userController.go
- web_app_backend/docs/docs.go
- web_app_backend/docs/swagger.json
- web_app_backend/docs/swagger.yaml
- web_app_backend/main.go
- web_app_backend/services/userService.go
user services
- **Swagger Integration**: Added comprehensive Swagger annotations to all userController functions, ensuring complete and clear API documentation. Improved visibility of user-related endpoints in Swagger UI.
- **Route Refactor**: Centralized and versioned all API routes under `/api/v1` in api.go for better organization and scalability. Simplified route definitions by grouping users, games, and scores logic while maintaining clear separation of concerns.
- **User Services Expansion**: Implemented delete and update functionalities in userService.go, completing CRUD operations for users. Integrated with userController, ensuring robust error handling for missing users.
These changes collectively improve API usability, scalability, and documentation, setting a strong foundation …
> feat: Major enhancements to API documentation, routing structure, and

- README.md
- web_app_frontend/Dockerfile
Can build and run the docker image / container.
The frontend doesn't work because of a backend API modification.
> Added frontend Dockerfile

- docker-compose.yml
- web_app_backend/Dockerfile
docker-compose to orchestrate the containers.
There is 3 containers, one for frontend, one for
backend and one for the DB.
> Create dockerfile for backend container and

- web_app_backend/api/api.go
- web_app_backend/controllers/gameController.go
- web_app_backend/controllers/scoreController.go
- web_app_backend/controllers/userController.go
- web_app_backend/database/database.go
- web_app_backend/docs/docs.go
- web_app_backend/docs/swagger.json
- web_app_backend/docs/swagger.yaml
- web_app_backend/main.go
- web_app_backend/middleware/authMiddleware.go
- web_app_backend/models/score.go
- web_app_backend/services/scoreService.go
- web_app_frontend/src/components/GameScores.vue
1. **Swagger Documentation**: Updated `@Router` and `@BasePath` annotations to align with `/api/...` endpoints, fixing the duplicate `/api/api` issue. 
2. **Authentication Middleware**: Applied `AuthMiddleware` to `/users`, `/games`, `/scores`, and `/home` routes to secure them with JWT validation. 
4. **New Home Route**: Added a protected `GET /home` endpoint returning a welcome message for authenticated users. 4. **Route Organization**: Grouped and structured routes logically to improve maintainability and consistency with Swagger docs.”
1. **JWT Integration**: Modified frontend to include the JWT token in the `Authorization` header for protected routes, ensuring secure API access.”
> Enhanced Security and Documentation Alignment for Backend and Frontend Integration

- README.md
Final formatting of the README file.
> Feature app deployment

- README.md
main features, linter used and enhanced the troubleshooting part.
> Upgraded README with the required informations : 

- web_app_frontend/src/components/PlayGame.vue
game ID
- Decoded JWT to extract the current user's ID and included it in the final score payload
- Incremented the gameID each time a new game starts to properly track different game sessions
- Ensured both user_id and the dynamically incremented game_id are sent to the backend when saving scores
> feat(game): correctly associate scores with current user and increment

- web_app_frontend/Dockerfile
- web_app_frontend/package-lock.json
- web_app_frontend/package.json
- web_app_frontend/src/components/RunningGame.vue
- web_app_frontend/src/router/index.js
- web_app_frontend/vite.config.js
Game route added in the index.js file
Phaser module (used for the game) path added to vite config.js to import correctly Phaser installation specified in the dockerfile with the line “RUN npm install phaser”.
> Integration of the running game in the project

- web_app_frontend/src/game/game.js
- web_app_frontend/src/game/gameEntities/Enemy.js
- web_app_frontend/src/game/gameEntities/Hero.js
- web_app_frontend/src/game/gameScenes/MainMenuScene.js
- web_app_frontend/src/game/gameScenes/MainScene.js
- web_app_frontend/src/game/gameScenes/PauseScene.js
- web_app_frontend/src/game/gameScenes/PreloaderScene.js
Added a Pause menu accessible by clicking Esc, from which you can you can return to the menu (PauseScene.js).
Added a Game over menu with display of player's score
> Added a Pause menu and a Game Over display

- web_app_frontend/src/game/game.js
- web_app_frontend/src/game/gameEntities/Enemy.js
- web_app_frontend/src/game/gameEntities/Hero.js
- web_app_frontend/src/game/gameScenes/GameOverScene.js
- web_app_frontend/src/game/gameScenes/MainScene.js
- web_app_frontend/src/game/gameScenes/PauseScene.js
- web_app_frontend/src/game/gameScenes/PreloaderScene.js
Added in the pause menu a button to restart a game .
Added a new game over scene with a button to restart a game and return to the menu.
It is no longer possible to pause in the game over screen.
> New pause menu and new game over menu with new buttons  

- web_app_frontend/src/components/Home.vue
- web_app_frontend/src/components/RunningGame.vue
- web_app_frontend/src/game/game.js
- web_app_frontend/src/router/index.js
Added a button and method for accessing the running game from the home page.
Changed the text of the buttons in the home page
> Added access to running game through a home page button  

- web_app_frontend/src/components/RunningGame.vue
- web_app_frontend/src/game/gameEntities/Enemy.js
- web_app_frontend/src/game/gameScenes/MainScene.js
- web_app_frontend/src/game/gameUtils/UserInputHandler.js
- Increasing the number of character in a character sequence every 100 meters travelled
- Addition of a message every 100 meters indicating the distance travelled and that the number of letters associated with enemies increased by one
- Increased size of text associated with enemies
- Word size is no longer random. It increases over time
> Addition of a message every 100 meters and modification of the enemy text system

- web_app_frontend/src/components/RunningGame.vue
- web_app_frontend/src/game/gameUtils/EnemyDetector.js
Added the buttons Home and Logout in the running game page
Added the tutorial for the running game
> Added the buttons Home and Logout in the running game page

- web_app_frontend/src/components/RunningGame.vue
Fixed a typo in the running game tutorial
Added a clarification on how the game works concerning the fact that th game become harder every 100 meters travelled by the character the player control
> Running Game tutorial correction

- web_app_backend/api/api.go
- web_app_backend/controllers/runningGameScoreController.go
- web_app_backend/services/runningGameScoreService.go
- web_app_frontend/src/components/Home.vue
- web_app_frontend/src/components/RunningGame.vue
- web_app_frontend/src/components/RunningGameScores.vue
- web_app_frontend/src/router/index.js
The following actions have been taken to ensure that the running game data is backed up :
- Creation of the RunningGameScores.vue file in the ‘components’ folder. This displays the results of the running game.
- Addition of the route associated with the RunningGameScores.vue file to index.js
- Addition of the GET method in api.go for the /runningScores route to retrieve data from the database
- Addition of GetAllRunningGameScores method to the runningGameScoreService.go file
- Addition of GetAllRunningGameScores method call in the runningGameScoreController.go file
- Addition of a button called "‘View Running Game Score’" in the home page for the player to view his scores for the running game
> Added the ability to save and display running game data

- web_app_backend/api/api.go
- web_app_backend/controllers/runningGameScoreController.go
- web_app_backend/models/running_game_score.go
- web_app_backend/services/runningGameScoreService.go
- web_app_frontend/README.md
- web_app_frontend/src/components/RunningGame.vue
- web_app_frontend/src/game/gameScenes/ScoreScene.js
To make this possible, the following actions were realised :
- Addition of the "topSeven" route to the api.go file
- Addition of GetTopRunningGameScores method to the runningGameScoreService.go file
- Importation of the GetTopRunningGameScores method to the runningGameScoreController.go file
- Modification of the RunningGameScore table model to add the User field In the running_game_score.go file
- In RunningGame.vue, correction of the omission of a final point (after the word "occcire")
- Added the ‘npm install phaser’ command to the README.md file in the root directory.
> Added the ability to retrieve and display the 7 highest scores among all the player of the running game
